import PageComponent from "@/components/Page/PageComponent";
import img1 from "./img/20200120-invest.webp"
import img2 from "./img/different-investment-types.jpg"
import img3 from "./img/180516153902-start-investing-640x360.jpg"
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Investment Analysis',
    description: 'Find out more about investment analysis',
}

const description = [
    "What a controversial statement, isn’t it? As the matter of fact, not really. Growth and continuous development is the natural process, you can’t challenge it. Either growth or stagnation, there is no other option. All physical or biological laws prove it. Stability is temporary illusion.",
    "Why do we say this?  Because in any organization there comes a time when the top management, analyzing the current state of the organization, determines highly prioritized directions for its further development. It’s a truly exciting process: building plans for future, searching new opportunities and complying changes. However, like everything in our life, this process should be performed carefully with all the procedures that economics prescribes so that you achieve some significant desirable results.",
    "Investment analysis involves reviewing a potential investment option to determine its future performance and how well it aligns with investor expectations. It's a core function of financial or investment analysts, and it involves selecting an investment option based on historical performance, market conditions, risk factors, and investor goals. This analysis aims primarily at evaluating investment options, identifying opportunities and assessing the risks and profitability that investment has in the portfolio.",
    "Financial analysis of the investment project is the most voluminous and labor-intensive. The project is accepted in terms of financial criteria, if the total cash flow generated by the investment covers its value taking into account the time value of money.",
    `<h6 className='font-bold mb-2'>For this analysis recommended indicators are the following:</h6>
    <ul className='list-disc list-inside'>
        <li>Net Present Value</li>
        <li>Internal Rate of Return</li>
        <li>Payback period, etc.</li>
    </ul>`
]

export default function IaPage() {
    return (
        <PageComponent title={'Investment analysis'}
            intro={'Expand or die.'}
            description={description}
            images={[img1, img2, img3]}
        />
    );
}